# Site Configuration
title: "üê∂ Dog with a Dev Blog"
description: "On the internet, nobody knows you're a dog and a cat and a latent space."
url: "https://blog.cani.ne.jp"
baseurl: ""

# Theme
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "light"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: false

sass:
  style: compressed

markdown: kramdown
highlighter: rouge

# Permalinks w/out categories
permalink: /:year/:month/:day/:title:output_ext

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore
  - README.md
  - "*.skbd"

# Plugins
plugins:
  - jekyll-archives
  - jekyll-auto-authors
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-target-blank

# jekyll-archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag-archive
    category: cat-archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'

# jekyll-auto-authors
autopages:
  enabled: true
  tags:
    enabled: false
  categories:
    enabled: true
    layouts:
      - 'cat-archive.html'
  collections:
    enabled: false
  authors:
    enabled: true
    data: '_data/authors.yaml'
    layouts:
      - 'author-archive.html'
    title: ':author'
    permalink: '/authors/:author/'
    slugify:
      mode: 'default'
      cased: false

# image-paths (local)
image_paths:
  base_url: /assets/img

# jekyll-paginate-v2 (required for jekyll-auto-authors)
pagination:
  enabled: false
