# Site Configuration
title: "üê∂ Dog with a Dev Blog"
description: "On the internet, nobody knows you're a dog and a cat in a latent space."
url: "https://blog.cani.ne.jp"
baseurl: ""

# Theme
remote_theme: riggraz/no-style-please
theme_config:
  appearance: "light"
  back_home_text: "~"
  back_link_text: ".."
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: false

sass:
  style: compressed
  load_paths:
    - ../jekyll-highlight-cards/_sass

markdown: kramdown
highlighter: rouge

# Permalinks w/out categories
permalink: /:year/:month/:day/:title:output_ext

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  garden:
    output: true
    permalink: /garden/:path:output_ext

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore
  - README.md
  - "*.skbd"

# Plugins
plugins:
  - jekyll-archives
  - jekyll-auto-authors
  - jekyll-feed
  - jekyll-highlight-cards
  - jekyll-paginate-v2
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# jekyll-archives
jekyll-archives:
  enabled:
    - tags
    - categories
  layouts:
    tag: tag-archive
    category: cat-archive
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
  collections:
    garden:
      enabled:
        - tags
      layouts:
        tag: garden-tag-archive
      permalinks:
        tag: '/garden/tags/:name/'

# jekyll-auto-authors
autopages:
  enabled: true
  tags:
    enabled: false
  categories:
    enabled: true
    layouts:
      - 'cat-archive.html'
  collections:
    enabled: false
  authors:
    enabled: true
    data: '_data/authors.yaml'
    layouts:
      - 'author-archive.html'
    title: ':author'
    permalink: '/authors/:author/'
    slugify:
      mode: 'default'
      cased: false

# jekyll-compress-html
compress_html:
  ignore:
    envs:
      - development

# image-paths (local)
image_paths:
  base_url: /assets/img

# href-decorator (local)
href_decorator:
  properties:
    - target: _blank
    - rel: noopener
  patterns:
    - '^https?://':
    - '/assets/':
    - '.+\.pdf$':
        properties:
          - download: true

# jekyll-paginate-v2 (required for jekyll-auto-authors)
pagination:
  enabled: false
